name: scan_o_matic 
description: QR/Barcode scanner application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.0.15
  flutter_slidable: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  url_launcher: ^6.2.5
  provider: ^6.1.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets: 
    - assets/logo.png

flutter_icons:
   image_path: "assets/logo.png"
   android: true